### ISSUE TITLE
Inconsistent sign/slide delete button locations

### ISSUE THREAD

**Issue by jameskerr** [chapmanu/signage#138]
For signs, the delete button is on the show page.
![screen shot 2016-03-21 at 9 59 58 am](https://cloud.githubusercontent.com/assets/3460638/13926918/b47fdf60-ef4b-11e5-8799-aea1a3d88c18.png)

For slides, the delete button is on the edit page.
![screen shot 2016-03-21 at 10 00 06 am](https://cloud.githubusercontent.com/assets/3460638/13926923/b8af6592-ef4b-11e5-90b7-76577b4d8282.png)

I recommend making the slides match the behavior of the signs.

**Comment by kaylaziegler** [comment]
This is a feature/design change. If product owners think it's worth addressing they can add a story for it. Not an issue.
