### ISSUE TITLE
Sponsor Banner appears as "None" when no sponsor is selected

### ISSUE THREAD

**Issue by khafa100** [chapmanu/signage#168]
Explained in user story: https://trello.com/c/lvGoSKhV

Possibly has two different "None" options when selecting a sponsor, the first as a 'sponsor' and the second as no sponsor.

**Comment by tatwell** [comment]
This was only an issue on Dev where someone had manually added a new sponsor named "None" to the database. If admin picks the top "None" from sponsor list for slide, slide will not show sponsor field as expected. However, if admin picked this second one further down the list, slide would display "None" in sponsor field.

The solution was simple: have an admin remove second None record:

As admin: login > Manage Sponsors > destroy

No code changes are required.
