### ISSUE TITLE
Crashes when users select image or video background/foreground for slide and don't upload anything.

### ISSUE THREAD

**Issue by kaylaziegler** [chapmanu/signage#179]
Pull request #185 

There is no error checking/handling for users adding different background media on the slide editing page. If the user selects one of the radio buttons for either video background/foreground or image background/foreground but does not upload anything, it crashes when they try to update/create the slide. Instead, when the user clicks to submit it should give a warning message that a file upload is required when video or image are selected.

**Comment by tatwell** [comment]
@kaylaziegler Can you provide a URL where this can be reproduced?

**Comment by kaylaziegler** [comment]
@tatwell The URL for the page that crashes would look something like this: https://signage.chapman.edu/slides/1959/edit
But if you try to go to any slide you didn't create it will tell you that you don't have permission to view the page. To reproduce the issue you would essentially have to make a new slide (https://signage.chapman.edu/slides/new) and click "Next" and that's the page with the issue (edit page).

**Comment by kaylaziegler** [comment]
Fixed this issue with PR #185
