### ISSUE TITLE
For events, audience and admission columns are mixed up.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/signage#188]
Trello story: https://trello.com/c/PEQlB1a3

In the `scheduled_items` table, the values for `audience` and `admission` are switched in all environments. See the example from the staging database below.

Example:

```
2.2.1 :005 > item = ScheduledItem.where.not(admission: '').first
  ScheduledItem Load (0.8ms)  SELECT  "scheduled_items".* FROM "scheduled_items" WHERE ("scheduled_items"."admission" != $1)  ORDER BY "scheduled_items"."id" ASC LIMIT 1  [["admission", ""]]
 => #<ScheduledItem id: 205928, date: "1/31/18", time: "11am", image: "7kg_TF4l.jpeg", name: "Event 1", content: "<div>This is my event!</div>", admission: "Orange Community", audience: "Free", location: nil, created_at: "2017-06-06 17:24:04", updated_at: "2017-06-07 19:44:14", slide_id: 278, play_on: nil, stop_on: nil, order: 0> 
2.2.1 :006 > item
 => #<ScheduledItem id: 205928, date: "1/31/18", time: "11am", image: "7kg_TF4l.jpeg", name: "Event 1", content: "<div>This is my event!</div>", admission: "Orange Community", audience: "Free", location: nil, created_at: "2017-06-06 17:24:04", updated_at: "2017-06-07 19:44:14", slide_id: 278, play_on: nil, stop_on: nil, order: 0> 
2.2.1 :007 > item.admission
 => "Orange Community" 
2.2.1 :008 > item.audience
 => "Free" 
```

As you can see in the above sample, Admission = Orange Community and Audience = Free.

Solution: Swap the `audience` and `admission` labels so that they match up with the correct values and migrate the database to reflect this update.

**Comment by kaylaziegler** [comment]
The field renaming and database migration to swap column names was addressed in PR #187. No additional issues that relate to this one have been brought up since, and I believe this should have been closed with the story.
