### ISSUE TITLE
Github is reporting security vulnerabilities

### ISSUE THREAD

**Issue by khafa100** [chapmanu/signage#198]
Story: https://trello.com/c/b6HQ7n5M

Github has identified potential security risks in our dependencies. The reported gems are as follows:
- rails 4.2.3 -> 4.2.7.1
- rails-html-sanitizer 1.0.2 -> 1.0.3
- rubyzip 1.1.7 -> 1.2.1
- net-ldap 0.11 -> 0.16.0

Updating these gems should fix this. Just need to make sure nothing breaks as a result and that all tests still pass.

**Comment by khafa100** [comment]
After updating all gems and rerunning all tests each time, all tests passed. However, there were 4 new deprecation warnings when there weren't any before the updates. I fixed 2 of them quite easily, but I'm still working on figuring out how to fix the other 2 deprecation warnings.

This is what I'm getting:
```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /Users/khafa100/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/railtie.rb:57)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /Users/khafa100/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/railtie.rb:58)
```

**Comment by khafa100** [comment]
In order to fix the deprecation warnings I had to update sass-rails from 5.0 to 5.0.6.

All tests now run without failing and without deprecation warnings.

**Comment by khafa100** [comment]
It seems the updates are causing conflicts with Capistrano, cause I can't deploy the feature branch to staging. I double checked to make sure that I was still able to deploy the master branch and I was successful.

I want to try to downgrade the `sass-rails` gem back to 5.0 from 5.0.6, as I believe that is the one causing the issues, but it keeps failing to do so.

**Comment by khafa100** [comment]
@tatwell I've googled it but the results were all from 2015. I guess it's still relevant though.

`inline_svg-0.6.1` didn't get upgraded, but when I looked at [this issue](https://github.com/jamesmartin/inline_svg/issues/25) and looked at their repository, I saw that they are at version 1.3.1.

I'll upgrade it to the latest and see if that fixes things. I was just wary of updating more gems than needed and increasing the risk of breaking something else as a result.

**Comment by tatwell** [comment]
@khafa100 It's generally a good thing to upgrade gems to the latest. The reason we, like many devs, procrastinate is that we don't want to deal with the inevitable issues that crop up, like this one.

Hopefully upgrading this gem will resolve issue without dropping us further into [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).

**Comment by khafa100** [comment]
I'm now able to deploy to staging after upgrading the `inline_svg` gem. There was a couple gems I had to upgrade on top of the Github dependency warnings, but everything is working as it should now.

Side note:
There is one test that inconsistently fails/passes. It only started doing that for me after upgrading the `inline_svg` gem. I'm not sure if that was already something that would sometimes happen or not.
```
1) Error:
Selecting slide orientation#test_0002_Standard slide can not select vertical orientation:
Capybara::ElementNotFound: Unable to find field "Chapman Username"
    test/support/integration_helpers.rb:7:in `block (2 levels) in sign_in'
    test/support/integration_helpers.rb:5:in `block in sign_in'
    test/support/integration_helpers.rb:3:in `sign_in'
    test/integration/slide_integration_test.rb:53:in `block (2 levels) in <class:SlideIntegrationTest>'
```

**Comment by tatwell** [comment]
@khafa100 It's a Capybara test so probably just a timeout issue. Double check it in the browser to make sure there are no issues.
