### ISSUE TITLE
Hide buttons based on user ability

### ISSUE THREAD

**Issue by jameskerr** [chapmanu/signage#67]

**Comment by jameskerr** [comment]
Use this gem http://blog.chaps.io/2015/11/13/role-based-authorization-in-rails.html?utm_source=rubyweekly&utm_medium=email

**Comment by kaylaziegler** [comment]
As far as I can tell, we already properly handle all user roles using the `cancancan` [gem.](https://github.com/CanCanCommunity/cancancan) It's unclear what specific "buttons" are being referred to here.
