### ISSUE TITLE
Only show the template picker on signs to super admins

### ISSUE THREAD

**Issue by jameskerr** [chapmanu/signage#89]
This is in the signs/_form file.

The template should not show dodge and wacubo templates to everyone.  Only a super admin should see that form field and be able to edit it.

**Comment by kaylaziegler** [comment]
We don't currently limit that field to only super admins, and I don't think it's something the product owners would necessarily want at this time. It hasn't been reported as an issue, and it's something that sign owners might want to do but sign owners aren't necessarily super admins. Closing.
