### ISSUE TITLE
Add image size helpers to slides form

### ISSUE THREAD

**Issue by jameskerr** [chapmanu/signage#92]
Determine some appropriate dimensions and indicate them on slides/_form

**Comment by kaylaziegler** [comment]
PR #141 covered this issue. Also see issue #91. Dimensions are indicated for foreground and background images on slide form.

**Comment by kaylaziegler** [comment]
PR #141 covered this issue. Also see issue #91. Dimensions are indicated for foreground and background images on slide form.

**Comment by kaylaziegler** [comment]
PR #141 covered this issue. Also see issue #91. Dimensions are indicated for foreground and background images on slide form.
